---
- id: circleci-config-validate
  name: CircleCI config validation
  description: Test if the CircleCI config is well formed.
  entry: circleci-config-validate.sh
  language: script
  files: ^.circleci/config.yml$

- id: circleci-config-pack
  name: CircleCI config pack
  description: Pack the config, creating the config.yml file
  entry: circleci-config-validate.sh
  language: script
  files: ^.circleci/config/*$

- id: poetry-pytest
  name: CircleCI config validation
  description: Use poetry to run pytest
  entry: poetry-pytest.sh
  language: script
  pass_filenames: false
  always_run: true

- id: hello-world
  name: hello world
  description: hello world
  entry: pre_commit_hooks/hello-world.py
  language: script
  types: [text]
  stages: [commit, push, manual]
