[tool.poetry]
name = "pre-commit-hooks"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
include = ["pre_commit_hooks/*"]

[tool.poetry.scripts]
hello-world="pre_commit_hooks.hello_world:main"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
